make it more Nim 1.4+ compatible
status-im/nim-chronos pull request #296
Opened 2022-07-19 09:36 UTC by narimiran

A continuation of https://github.com/status-im/nimbus-eth2/pull/3888

Rationale (from that link):

> Currently (the latest commit in unstable branch), the CI log for the 1.6 branch has **107.000 lines**.
Removing every hint about cannot raise 'Defect' (including the ones in the vendor directory) leaves **16.000 lines**. 85% off.

2022-07-26 14:52 UTC, narimiran commented
Anything stopping this from being merged?

2022-08-03 12:03 UTC, Menduist requested changes
Could you also fix
https://github.com/status-im/nim-chronos/blob/master/chronos/asyncmacro2.nim#L184-L200
(have already been fixed [here](https://github.com/status-im/nim-chronos/pull/251/files#diff-c1e1958e958f530246209b2176ae811a267b4c8d9ee8ffeac0fadf4a6abab460R242-R252), you can do something similar)

& asyncfutures2

Currently, every async procedure is causing 2 "XCannotRaiseY" warnings, which is not very viable

2022-08-03 16:49 UTC, narimiran commented
> Could you also fix

Can that be part of a follow-up PR?
Maybe together with some fixes for `UnusedImport`, `CStringConv`, etc.?

2022-08-03 16:51 UTC, Menduist approved these changes
sure

2022-08-06 10:56 UTC, merged